nginx:
  restart: always
  image: 'hongbinfu/nginx:1.9.9'
  ports:
      - '80:80'
  links:
      - phpfpm
      - mysql
  volumes:
      - /etc/localtime:/etc/localtime
      - ../src:/www
      - ./logs/nginx:/tmp/logs
      - ./vhost:/etc/nginx/vhost
      - ./nginx.conf:/etc/nginx/nginx.conf
phpfpm:
  restart: always
  image: 'hongbinfu/php:5.6.17'
  image: "8ce3bc7c0d9e"
  ports:
      - '9000:9000'
  links:
      - mysql
  volumes:
      - /etc/localtime:/etc/localtime
      - ../src:/www
      - ./logs/php:/tmp/logs
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
mysql:
  restart: always
  image: "mysql"
  ports:
      - '3306:3306'
  volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/var/lib/mysql
      - ./logs/mysql:/tmp/logs
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
  environment:
      - MYSQL_ROOT_PASSWORD=lovecalvin
      - MYSQL_DATABASE=wf_online
      - MYSQL_USER=webworker
      - MYSQL_PASSWORD=wf_online
