nginx:
  restart: always
  image: 'hongbinfu/nginx:1.9.9'
  ports:
      - '80:80'
      - '10080:10080'
      - '10081:10081'
  links:
      - phpfpm
      - mysql
  volumes:
      - /etc/localtime:/etc/localtime
      - ../src:/www
      - ./logs/nginx:/tmp/logs
      - ./vhost:/etc/nginx/vhost
      - ./nginx.conf:/etc/nginx/nginx.conf
phpfpm:
  restart: always
  image: 'hongbinfu/php:5.6.17'
  # ports:
  #     - '9000:9000'
  links:
      - mysql
      - redis
  volumes:
      - /etc/localtime:/etc/localtime
      - ../src:/www
      - ./logs/php:/tmp/logs
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./wf_online_release.sql:/docker-entrypoint-initdb.d/wf_online_release.sql
mysql:
  restart: always
  image: "mysql"
  ports:
      - '3306:3306'
  volumes:
      - /etc/localtime:/etc/localtime
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/tmp/logs
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
  environment:
      - MYSQL_ROOT_PASSWORD=lovecalvin
      - MYSQL_DATABASE=wf_online
      - MYSQL_USER=webworker
      - MYSQL_PASSWORD=wf_online
redis:
  restart: always
  image: "redis"
  volumes:
      - /etc/localtime:/etc/localtime
      - ./data/redis:/data
